image:
  repository: hyndav/shell-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: LoadBalancer
  port: 80
  targetPort: 4000

ingress:
  enabled: false

extraEnvVars: []
