apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "shell-app.fullname" . }}-s3-upload
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-failed
spec:
  template:
    spec:
      containers:
        - name: upload-shell
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Uploading shell SSR to S3"
              aws s3 sync /app/build s3://$S3_BUCKET --delete
              aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DIST_ID" --paths "/*"
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: accessKeyId
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secretAccessKey
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: s3-config
                  key: bucket
            - name: CLOUDFRONT_DIST_ID
              valueFrom:
                configMapKeyRef:
                  name: s3-config
                  key: distributionId
      restartPolicy: Never
  backoffLimit: 1
