apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shell-app.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "shell-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "shell-app.name" . }}
    spec:
      containers:
        - name: shell-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 4000
          env:
            {{- range .Values.extraEnvVars }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
